name: WaterGrid Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.9.10
          - 3.10.3
          - 3.11.0-alpha.5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m unittest discover -s test -p '*.py'
  coverage:
    name: Coverage report
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.3
      - name: Install dependencies
        run: |
          pip install coverage
          pip install -r requirements.txt
      - name: Generate coverage report
        run: |
          coverage run --source=watergrid -m unittest discover -s test -p '*.py'
          coverage xml -o coverage.xml
      - name: Submit coverage report
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 29a27fc4eb61dd439f58c906409779d64a5a760a37b8b118a643959621727e3d
        with:
          coverageCommand: coverage report
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.3
      - name: Install dependencies
        run: pip install black
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          auto_fix: true
