name: Sphinx
on:
  push:
    branches:
      - main
jobs:
  sphinx-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.1
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Sphinx
        run: |
          pip install -r docs/requirements.txt
      - name: Build documentation
        run: |
          cd docs
          make html
          cd _build/html
          touch .nojekyll
      - name: Push docs to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: ./docs/_build/html
