name: Sphinx
on:
  push:
    branches:
      - main
jobs:
  sphinx-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Sphinx
        run: |
          pip install -r docs/requirements.txt
      - name: Build documentation
        run: |
          cd docs
          make html
      - name: Push docs to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.2.3
        with:
          branch: gh-pages
          folder: ./docs/_build/html
