name: PyPI Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install deploy dependencies
        run: python -m pip install build wheel
      - name: Build release
        shell: bash -l {0}
        run: python setup.py sdist bdist_wheel
      - name: Publish release to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}